In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('Scores.csv')

In [3]:
data

,Full Name,Happy Score,Sad Score,Neutral Score,Passionate Score,Angry Score
0,Hamed Hatami,6.00,4.4,3.40,6.40,4.2
1,Arian Yazdanparast,7.00,3.5,5.00,6.75,3.5
2,MohammadAli Karbaschi,6.60,4.6,3.20,8.20,2.8
3,Kasra Amani,6.25,4.5,6.25,6.75,6.5
4,MohammadAli Khodabandehlou,7.00,3.0,5.25,3.00,1.5
...,...,...,...,...,...,...
69,Alireza Daqiq,6.20,4.0,5.80,4.20,4.0
70,Sina Tavakkoli,3.33,7.0,4.33,5.00,2.0
71,Mohammad sharif Ashna,NaN,NaN,NaN,NaN,NaN
72,Karaneh Keypoor,NaN,NaN,NaN,NaN,NaN
73,Pouya Lahabi,NaN,NaN,NaN,NaN,NaN

In [11]:
data_dict = {}
for row in data.iterrows():
    temp_list_for_each_person = []
    happy_score = row[1]["Happy Score"]
    temp_list_for_each_person.append(str(row[1]["Happy Score"]))
    temp_list_for_each_person.append(str(row[1]["Sad Score"]))
    temp_list_for_each_person.append(str(row[1]["Angry Score"]))
    temp_list_for_each_person.append(str(row[1]["Neutral Score"]))
    temp_list_for_each_person.append(str(row[1]["Passionate Score"]))
    export_string = '#'.join(temp_list_for_each_person)
    data_dict[row[1]["Full Name"]] = export_string
    
data_dict

{'Hamed Hatami': '6.0#4.4#4.2#3.4#6.4',
 'Arian Yazdanparast': '7.0#3.5#3.5#5.0#6.75',
 'MohammadAli Karbaschi': '6.6#4.6#2.8#3.2#8.2',
 'Kasra Amani': '6.25#4.5#6.5#6.25#6.75',
 'MohammadAli Khodabandehlou': '7.0#3.0#1.5#5.25#3.0',
 'Hamidreza Yaghoubi': '7.5#2.0#1.5#1.5#3.5',
 'Masih Beigi': '6.33#3.0#4.0#6.66#5.66',
 'Amirhossein Ranjbar': '6.6#4.4#1.8#6.0#6.6',
 'Sara Zahedi': '7.2#4.2#3.6#4.2#5.2',
 'Mohammad Jafari': '4.5#5.5#3.0#8.0#6.0',
 'Mahdiyeh Ebrahimpour': '2.6#8.2#7.0#4.8#3.4',
 'Amirreza Ghasemi': '5.5#4.75#2.75#5.5#2.75',
 'Yeganeh Yazdi Zadeh': '5.0#6.33#3.0#7.66#4.33',
 'Ehsan Movaffagh': '5.4#5.4#3.0#5.4#5.2',
 'Bardia Taheri': '5.66#3.66#2.33#6.33#4.33',
 'Bardia Mohammadi': '4.66#4.66#4.0#5.66#3.0',
 'Mahdi Siami': '7.5#2.5#3.0#4.5#5.5',
 'Mohsen Ghasemi': '4.5#8.0#4.5#6.0#6.5',
 'Donya Roshanzamir': '7.0#4.6#5.4#6.0#7.6',
 'Seyed Mohammad Mahdi Hatami': '7.66#2.66#1.33#7.66#6.66',
 'Romina Ayoubi': '6.25#4.25#4.25#4.5#5.5',
 'Mahdi Samiei ': '4.0#7.0#5.0#3.0#3.0',
 'Zahra Abdi': '7.33#4.33#3.66#4.66#6.0',
 'Melica Kianfard': '6.0#5.0#4.0#7.5#6.5',
 'Aref Zarghani': '6.2#5.0#4.4#5.8#4.4',
 'Mahdi Alizadeh': '7.0#4.5#2.5#3.75#6.0',
 'Soheil Nazari': '3.75#6.0#3.25#5.5#3.75',
 'Sina Elahimanesh': '8.8#2.6#1.8#5.0#8.2',
 'MohammadAli MohammadKhani': '5.8#4.8#4.2#6.0#4.4',
 'Zohreh Abbasi': '6.33#6.66#4.0#3.66#7.0',
 'Kahbod Aeini': '4.8#6.0#3.4#4.6#6.2',
 'Mohadeseh Khosravi': '4.5#5.5#4.75#4.75#8.25',
 'Majid Taherkhani': '7.0#3.5#3.5#6.0#7.5',
 'Sara Khosravi': '4.4#7.2#1.6#1.8#6.2',
 'Iman Mohammadi': '6.0#5.33#2.33#4.0#5.33',
 'Arshak Rezvani': '7.75#4.5#4.0#4.25#8.5',
 'Mikaeel Ghorbani': '6.5#3.25#1.0#3.5#4.75',
 'Helia Akhtarkavian': '7.0#4.0#1.66#6.0#6.33',
 'Zahra Arjmand': '7.0#6.6#2.4#2.8#5.0',
 'Ali Asghar Ghanati': '4.75#3.5#1.25#5.5#4.75',
 'Sepehr Ilami': '7.0#2.25#2.5#4.0#8.0',
 'Hirbod Behnam': '6.25#3.25#1.5#5.5#5.75',
 'Zahra Guilandokht': '5.5#4.5#5.0#5.0#7.0',
 'Ehsan Rahmani': 'nan#nan#nan#nan#nan',
 'Mishka Nouri': '4.75#4.75#5.75#6.0#8.25',
 'Niaz Ghafari': '6.0#6.66#4.0#4.66#6.0',
 'Setayesh Esmaili': '6.0#6.25#3.75#2.5#8.0',
 'Atena Nouri': '8.0#3.25#2.75#4.25#8.0',
 'Alireza Foroodnia': '4.5#4.5#1.0#4.0#4.75',
 'Hamraz Arafati': '7.2#4.6#3.4#4.2#7.5',
 'Amirhossein Razlighi': '3.66#6.33#4.33#5.0#6.33',
 'Mohammad Amin Ghasemzadeh': '7.25#2.0#1.75#3.0#5.5',
 'Mehrad Milanloo': '7.2#3.4#3.2#4.0#5.2',
 'Amirreza Fallahnejad': '5.5#4.0#5.5#7.0#4.75',
 'Alireza Hosseinkhani': '7.2#3.0#1.6#6.4#5.0',
 'Mohammadreza Zareihoor': '6.4#4.8#3.0#6.8#6.4',
 'Mohammadamin Aryan': '7.25#4.75#4.5#4.0#7.75',
 'Mohammadmahdi Mirzaei ': '7.5#3.0#2.5#3.5#7.0',
 'Fatemeh Asgari': '6.0#5.5#2.5#8.5#3.5',
 'Rezvan Pourmehdi': '3.0#7.25#4.75#4.75#4.0',
 'Mahdi Akhi': '7.25#2.25#3.75#4.5#9.0',
 'Ali Shokri': '6.6#2.8#1.6#7.0#4.4',
 'Seyyed Mahdi Faghih': '7.33#1.66#1.33#7.66#3.0',
 'Hedieh Raeisi ': '5.0#6.5#4.0#7.0#4.5',
 'Hooman Keshvari': '8.66#2.66#2.33#2.33#8.33',
 'Kamyar Kazari': '8.0#2.0#2.5#2.5#5.5',
 'Amirhosein Barati': '6.0#4.33#2.66#7.0#5.33',
 'Aidin Hosseini Nasab': '6.66#4.33#6.33#6.66#5.0',
 'Shakiba Rasooli': '4.0#7.2#3.2#5.2#6.6',
 'Alireza Daqiq ': '6.2#4.0#4.0#5.8#4.2',
 'Sina Tavakkoli': '3.33#7.0#2.0#4.33#5.0',
 'Mohammad sharif Ashna': 'nan#nan#nan#nan#nan',
 'Karaneh Keypoor': 'nan#nan#nan#nan#nan',
 'Pouya Lahabi': 'nan#nan#nan#nan#nan'}

In [12]:
import json 
with open("friends.txt", "w") as fp:
    json.dump(data_dict, fp)  # encode dict into JSON
print("Done writing dict into .txt file")

Done writing dict into .txt file